#%RAML 1.0 DataType
type: object
additionalProperties: false
example: !include ../examples/game.json
description: These fields represent information about a game object

properties:
  id: appIDType
  title: string