#%RAML 1.0 DataType

type: string
maxLength: 17
minLength: 17
pattern: "[0-9]{17}"
description: A unique number that is assigned to every new account created on steampowered.com, to find out your own account information try out steamdb.info

example: "12345678901234567"
